name: Set up Pyodide

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install panel
          pip install biopython
      - name: Convert to Pyodide
        run: |
          panel convert index.py --to pyodide-worker --out docs/app/ --title SynRecoder --pwa